### ISSUE TITLE
UI full text search autocomplete

### ISSUE THREAD

**Issue by rporrini** [rporrini/abstat#84]
http://www.andornot.com/blog/post/Advanced-autocomplete-with-Solr-Ngrams-and-Twitters-typeaheadjs.aspx

https://cwiki.apache.org/confluence/display/solr/Suggester

----------------------------------------
- Bitbucket: https://bitbucket.org/rporrini/schema-summaries/issue/59
- Originally reported by: Riccardo Porrini
- Originally created at: 2015-08-11T15:25:48.156

**Comment by rporrini** [comment]
spike branch autocomplete-spike

**Comment by rporrini** [comment]
beware of this:

 http://abstat.disco.unimib.it/api/v1/autocomplete/concepts?dataset=dbpedia-3.9-infobox&q=city%20of

here is the stacktrace:

09-10-2015 13:47:57,386 [qtp1162754992-16] ERROR - processing request: /api/v1/autocomplete/concepts
java.net.URISyntaxException: Illegal character in query at index 69: http://localhost:8891//solr/indexing/concept-suggest?q=URI_ngram:city of&fq=dataset:dbpedia-3.9-infobox
	at java.net.URI$Parser.fail(URI.java:2829)
	at java.net.URI$Parser.checkChars(URI.java:3002)
	at java.net.URI$Parser.parseHierarchical(URI.java:3092)
	at java.net.URI$Parser.parse(URI.java:3034)
	at java.net.URI.<init>(URI.java:595)
	at it.unimib.disco.summarization.web.tests.ClientCommunication.httpGet(ClientCommunication.java:29)
	at it.unimib.disco.summarization.web.SolrConnector.query(SolrConnector.java:11)
	at it.unimib.disco.summarization.web.ConceptsApi.getResponseFromConnector(ConceptsApi.java:18)
	at it.unimib.disco.summarization.web.JsonResponse.sendResponse(JsonResponse.java:21)
	at it.unimib.disco.summarization.web.Application.handle(Application.java:26)

**Comment by brando91** [comment]
Implemented autocomplete for concepts

**Comment by rporrini** [comment]
just deployed the autocomplete for properties
